export const HTTP_STATUS = {
  OK: 200,
  NO_CONTENT: 204,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

export const EMPTY_API_KEY = "EMPTY API KEY";

export const FIVE_MINUTE_SECOND = 60 * 5;
export const FIVE_MINUTE_MILLISECOND = FIVE_MINUTE_SECOND * 1e3;
